### ISSUE TITLE
URL to resource planner is written wrong

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/business-resource-planner-demo#6]
Nit pick.  I'd fix it if I had access OR I can do a pull request and submit the changes.  Your choice.

**Comment by eschabell** [comment]
PR's are always welcome, that's how github works and these demo projects grow! ;)

PS. Be sure to include "Fixes #6" in the final commit message of your PR, that will close this issue automagically.

**Comment by eschabell** [comment]
Fixed by #8.
