### ISSUE TITLE
Suggestion - This demo doesn't show how it works.

### ISSUE THREAD

**Issue by alberttwong** [jbossdemocentral/business-resource-planner-demo#7]
I think there needs some explanation about this demo.

For instance, how do you load the data?   How do you implement the algorithm?  Why should you solve this problem using BRMS as opposed to use a big data solution?    How would OptaPlanner be used in an enterprise environment?

**Comment by alberttwong** [comment]
Maybe not best place to ask these questions.   It's just that the demo doesn't explain a lot of what I'm seeing unlike the other demos (cool store).

**Comment by eschabell** [comment]
This does nothing more than provide a quicker and easier installation of the Business Resource Planner demo example project that is a community OptaPlanner component. It is not really disectable, just shows what it can do visually. 

If you need more details on this component within the JBoss BRMS product, you will need to attend or look up some of the training that Geoffrey gives/gave this year.

Reach out to me for more details on my Red Hat email.
